language: android

android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-28"

before_script:
  - chmod +x gradlew
  - echo "sdk.dir=$ANDROID_HOME" > local.properties

script: "./gradlew build"
